version: '3.8'

services:
  chatbot-legal:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    volumes:
      - ./docs_upload:/app/docs_upload
      - ./registro_chat.xlsx:/app/registro_chat.xlsx
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - qdrant
    networks:
      - chatbot-network

  # Opcional: Qdrant local (comentar si usas Qdrant Cloud)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - chatbot-network

volumes:
  qdrant_data:

networks:
  chatbot-network:
    driver: bridge
